<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="fca78d6b-0e2b-43e6-9a8c-6d504e8b3a6c" name="Sprenger@SPRENGER-PC 2015-01-08 16:48:06" runUser="Sprenger-PC\Sprenger" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2006">
  <TestRunConfiguration name="Ejecución de pruebas local" id="36892c21-a994-4aa5-9de0-3d11072462b5">
    <Description>Configuración de ejecución de pruebas predeterminada para una ejecución de pruebas local.</Description>
    <Deployment runDeploymentRoot="C:\GHAU\GHAU\TestResults\Sprenger_SPRENGER-PC 2015-01-08 16_48_06">
      <DeploymentItem filename="C:\GHAU\GHAU\GHAU_CapaDatos\bin\Release\GHAU_CapaDatos.dll" />
      <DeploymentItem filename="C:\GHAU\GHAU\GHAU_CapaNegocio\bin\Release\GHAU_CapaNegocio.dll" />
    </Deployment>
    <TestTypeSpecific />
  </TestRunConfiguration>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <Times creation="2015-01-08T16:48:06.8687376-03:00" queuing="2015-01-08T16:48:08.7828470-03:00" start="2015-01-08T16:48:09.0558626-03:00" finish="2015-01-08T16:48:27.8359368-03:00" />
  <TestDefinitions>
    <UnitTest name="ingreso_eventoTest" storage="c:\ghau\ghau\pruebas unitarias\bin\release\pruebas unitarias.dll" id="d5d67204-57d2-12f7-3523-d5391002f656">
      <Css projectStructure="" iteration="" />
      <Owners>
        <Owner name="" />
      </Owners>
      <Execution id="617e6dc5-2d6c-4abb-95fa-3837dfab0594" />
      <TestMethod codeBase="C:\GHAU\GHAU\Pruebas Unitarias\bin\Release\Pruebas Unitarias.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Pruebas_Unitarias.EventosTest, Pruebas Unitarias" name="ingreso_eventoTest" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Resultados que no están en la lista" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="Todos los resultados cargados" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="d5d67204-57d2-12f7-3523-d5391002f656" executionId="617e6dc5-2d6c-4abb-95fa-3837dfab0594" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="617e6dc5-2d6c-4abb-95fa-3837dfab0594" testId="d5d67204-57d2-12f7-3523-d5391002f656" testName="ingreso_eventoTest" computerName="SPRENGER-PC" duration="00:00:17.8525071" startTime="2015-01-08T16:48:09.2768753-03:00" endTime="2015-01-08T16:48:27.6749276-03:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d">
      <Output>
        <ErrorInfo>
          <Message>El método de prueba Pruebas_Unitarias.EventosTest.ingreso_eventoTest produjo la excepción:  System.IndexOutOfRangeException: No hay ninguna fila en la posición 1..</Message>
          <StackTrace>    en System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   en System.Data.RBTree`1.get_Item(Int32 index)
   en System.Data.DataRowCollection.get_Item(Int32 index)
   en Pruebas_Unitarias.EventosTest.ingreso_eventoTest() en C:\GHAU\GHAU\Pruebas Unitarias\EventosTest.vb:línea 110
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>